In [2]:
import numpy as np

In [14]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3],[4,5,6],[6,7,8]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [4]:
print(escalar)

5.679


In [5]:
escalar.shape

AttributeError: 'float' object has no attribute 'shape'

In [6]:
vector.shape      # 3 Columnas 

(3,)

In [7]:
print(vector)

[1 2 3]


In [15]:
matriz.shape        # 2 Filas y 2 Columnas 

(2, 2)

In [9]:
print(matriz)

[[1 2]
 [3 4]]


In [11]:
print(matriz.size)

4


In [12]:
print(tensor.shape)

(3, 3, 3)


In [65]:
# (numero de matrices, numero_filas, número_columnas)

#tensor[0,:,:]  #donde se recupera la matriz 1
#tensor[1,:,:]  #se recupera la matriz 2
tensor[2,:,:]  #se recupera la tercera matriz


array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])