In [2]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [7]:
print(f'{A} \n')
print(B)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
print(A.shape)

(4, 3)


In [5]:
print(B.shape)

(3, 2)


In [6]:
C = A.dot(B)
C

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

Los valores son:
- 1x2+2x5+3x11= 45
- 1x3+2x7+3x13=56
- 4x2+5x5+6x11=99
- 4x3+5x7+6x11=125
- 7x2+8x5+9x11=153
- 7x3+8x7+9x13=194
- 10x2+11x5+12x11=207
- 10x3+11x7+12x13=263

In [6]:
D = B.dot(A)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

In [3]:
A = np.array([[1,2],[3,4],[5,6]])    #Cuando coinciden en dimensiones se pueden los dos escenarios 
B = np.array([[1,2,3],[4,5,6]])

In [5]:
print(A.shape)
print(B.shape)

(3, 2)
(2, 3)


In [12]:
print(A.dot(B))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [13]:
print(B.dot(A))

[[22 28]
 [49 64]]
