In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
print(B)

[[1 3]
 [2 1]]


In [9]:
AB_t = A.dot(B).T

In [10]:
B_tA_t = B.T.dot(A.T)

In [11]:
print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [12]:
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]
